# Form implementation generated from reading ui file '/home/colin/Python/Projects/Pycharm/Other/Learning/LearningQt/src/gui/ui/register/register_view.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(903, 678)
        self.centralwidget = QtWidgets.QWidget(RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.RegisterViewTitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.RegisterViewTitleLabel.setGeometry(QtCore.QRect(20, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.RegisterViewTitleLabel.setFont(font)
        self.RegisterViewTitleLabel.setObjectName("RegisterViewTitleLabel")
        self.RegisterViewDescriptionLabel = QtWidgets.QLabel(self.centralwidget)
        self.RegisterViewDescriptionLabel.setGeometry(QtCore.QRect(20, 70, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RegisterViewDescriptionLabel.setFont(font)
        self.RegisterViewDescriptionLabel.setObjectName("RegisterViewDescriptionLabel")
        self.RegisterFormFirstnameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.RegisterFormFirstnameLineEdit.setGeometry(QtCore.QRect(20, 170, 311, 41))
        self.RegisterFormFirstnameLineEdit.setObjectName("RegisterFormFirstnameLineEdit")
        self.RegisterFormFirstnameLabel = QtWidgets.QLabel(self.centralwidget)
        self.RegisterFormFirstnameLabel.setGeometry(QtCore.QRect(20, 150, 67, 17))
        self.RegisterFormFirstnameLabel.setObjectName("RegisterFormFirstnameLabel")
        self.RegisterFormUsernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.RegisterFormUsernameLabel.setGeometry(QtCore.QRect(20, 260, 67, 17))
        self.RegisterFormUsernameLabel.setObjectName("RegisterFormUsernameLabel")
        self.RegisterFormUsernameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.RegisterFormUsernameLineEdit.setGeometry(QtCore.QRect(20, 280, 851, 41))
        self.RegisterFormUsernameLineEdit.setObjectName("RegisterFormUsernameLineEdit")
        self.RegisterFormSuffixLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.RegisterFormSuffixLineEdit.setGeometry(QtCore.QRect(340, 170, 211, 41))
        self.RegisterFormSuffixLineEdit.setObjectName("RegisterFormSuffixLineEdit")
        self.RegisterFormLastnameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.RegisterFormLastnameLineEdit.setGeometry(QtCore.QRect(560, 170, 311, 41))
        self.RegisterFormLastnameLineEdit.setObjectName("RegisterFormLastnameLineEdit")
        self.RegisterFormSuffixLabel = QtWidgets.QLabel(self.centralwidget)
        self.RegisterFormSuffixLabel.setGeometry(QtCore.QRect(340, 150, 67, 17))
        self.RegisterFormSuffixLabel.setObjectName("RegisterFormSuffixLabel")
        self.RegisterFormLastnameLabel = QtWidgets.QLabel(self.centralwidget)
        self.RegisterFormLastnameLabel.setGeometry(QtCore.QRect(560, 150, 67, 17))
        self.RegisterFormLastnameLabel.setObjectName("RegisterFormLastnameLabel")
        self.RegisterFormPasswordLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.RegisterFormPasswordLineEdit.setGeometry(QtCore.QRect(20, 390, 851, 41))
        self.RegisterFormPasswordLineEdit.setObjectName("RegisterFormPasswordLineEdit")
        self.RegisterFormPasswordLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.RegisterFormPasswordLabel_2.setGeometry(QtCore.QRect(20, 370, 67, 17))
        self.RegisterFormPasswordLabel_2.setObjectName("RegisterFormPasswordLabel_2")
        self.RegisterFormSubmitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.RegisterFormSubmitBtn.setGeometry(QtCore.QRect(320, 520, 191, 71))
        self.RegisterFormSubmitBtn.setObjectName("RegisterFormSubmitBtn")
        RegisterWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(RegisterWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 903, 22))
        self.menuBar.setObjectName("menuBar")
        RegisterWindow.setMenuBar(self.menuBar)
        self.actionLogin = QtGui.QAction(RegisterWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionRegister = QtGui.QAction(RegisterWindow)
        self.actionRegister.setObjectName("actionRegister")

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "MainWindow"))
        self.RegisterViewTitleLabel.setText(_translate("RegisterWindow", "TextLabel"))
        self.RegisterViewDescriptionLabel.setText(_translate("RegisterWindow", "TextLabel"))
        self.RegisterFormFirstnameLabel.setText(_translate("RegisterWindow", "TextLabel"))
        self.RegisterFormUsernameLabel.setText(_translate("RegisterWindow", "TextLabel"))
        self.RegisterFormSuffixLabel.setText(_translate("RegisterWindow", "TextLabel"))
        self.RegisterFormLastnameLabel.setText(_translate("RegisterWindow", "TextLabel"))
        self.RegisterFormPasswordLabel_2.setText(_translate("RegisterWindow", "TextLabel"))
        self.RegisterFormSubmitBtn.setText(_translate("RegisterWindow", "PushButton"))
        self.actionLogin.setText(_translate("RegisterWindow", "Login"))
        self.actionRegister.setText(_translate("RegisterWindow", "Register"))
