# Form implementation generated from reading ui file '/home/colin/Python/Projects/Pycharm/Other/Learning/LearningQt/src/gui/ui/welcome-user/welcome-user_view.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Welcome_userWindow(object):
    def setupUi(self, Welcome_userWindow):
        Welcome_userWindow.setObjectName("Welcome_userWindow")
        Welcome_userWindow.resize(903, 678)
        self.centralwidget = QtWidgets.QWidget(Welcome_userWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.WelcomeUserLabel = QtWidgets.QLabel(self.centralwidget)
        self.WelcomeUserLabel.setGeometry(QtCore.QRect(30, 30, 111, 31))
        self.WelcomeUserLabel.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.WelcomeUserLabel.setFont(font)
        self.WelcomeUserLabel.setObjectName("WelcomeUserLabel")
        Welcome_userWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(Welcome_userWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 903, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuHome = QtWidgets.QMenu(self.menuBar)
        self.menuHome.setObjectName("menuHome")
        Welcome_userWindow.setMenuBar(self.menuBar)
        self.actionLogin = QtGui.QAction(Welcome_userWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionRegister = QtGui.QAction(Welcome_userWindow)
        self.actionRegister.setObjectName("actionRegister")
        self.menuBar.addAction(self.menuHome.menuAction())

        self.retranslateUi(Welcome_userWindow)
        QtCore.QMetaObject.connectSlotsByName(Welcome_userWindow)

    def retranslateUi(self, Welcome_userWindow):
        _translate = QtCore.QCoreApplication.translate
        Welcome_userWindow.setWindowTitle(_translate("Welcome_userWindow", "MainWindow"))
        self.WelcomeUserLabel.setText(_translate("Welcome_userWindow", "TextLabel"))
        self.menuHome.setTitle(_translate("Welcome_userWindow", "My account"))
        self.actionLogin.setText(_translate("Welcome_userWindow", "Login"))
        self.actionRegister.setText(_translate("Welcome_userWindow", "Register"))
